### ISSUE TITLE
Job submission fails but no clear message on what is wrong.

### ISSUE THREAD

**Issue by guus2006** [Azure/BatchExplorer-data#30]
I am creating a job with Maya/Vray template (tried both CentOS and Windows). Fill in the details and I get the following error: 

"
The value provided for one of the properties in the request body is invalid.

Request ID | 9f795135-1d3f-4592-bd81-2eb20db81ae3
-- | --
Time | Mon Nov 12 2018 14:53:12 GMT+0100 (CET)
"

There is no information on what is wrong with my submission information.
```
{"name":"BatchExplorer Renderer","hostname":"MacBookJR.local","pid":22445,"level":50,"error":"Unknown Python server error format","msg":"{ err: undefined }","time":"2018-11-12T13:53:11.684Z","v":0}
{"name":"BatchExplorer Renderer","hostname":"MacBookJR.local","pid":22445,"level":50,"error":"Error while executing button action","msg":"{ err: \n   { status: undefined,\n     statusText: undefined,\n     code: null,\n     message: 'The value provided for one of the properties in the request body is invalid.',\n     details: [],\n     requestId: '9f795135-1d3f-4592-bd81-2eb20db81ae3',\n     timestamp: 2018-11-12T13:53:12.993Z,\n     original: \n      { code: 400,\n        message: 'The value provided for one of the properties in the request body is invalid.\\nRequestId:9f795135-1d3f-4592-bd81-2eb20db81ae3\\nTime:2018-11-12T13:53:12.9937388Z',\n        data: [Object] } } }","time":"2018-11-12T13:53:11.687Z","v":0}
{"name":"BatchExplorer Renderer","hostname":"MacBookJR.local","pid":22445,"level":50,"error":"[BL] Uncaught exception:","msg":"{ err: 'The value provided for one of the properties in the request body is invalid.' }","time":"2018-11-12T13:53:11.695Z","v":0}
```
OS: OS X 10.14.1
version Batch explorer: Version 0.18.4-stable.154 (0.18.4-stable.154.154)

**Comment by timotheeguerin** [comment]
I transferred this issue into the data repo

**Comment by ascobie** [comment]
Hi @jeroenroodnat, 

I have updated the templates to use AZ Copy in the job preparation task. Please check and let me know that you are unblocked. You might need to refresh the templates in BatchExplorer, you can do this by clicking refresh in the Gallery page: 

![image](https://user-images.githubusercontent.com/10934358/48388158-40352680-e75d-11e8-951c-9e6af2bbbb94.png)

Send me an email if you have any further issues. 

Andrew

**Comment by guus2006** [comment]
Refresh solves the issue and job is submitted now. thank you
